// <auto-generated />
using ArtVistaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtVistaAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230706135522_Update-Bid")]
    partial class UpdateBid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtVistaAPI.Models.ArtModel", b =>
                {
                    b.Property<int>("art_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("art_id"));

                    b.Property<string>("art_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("art_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artist_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("art_id");

                    b.ToTable("Art");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.ArtistPortfolioModel", b =>
                {
                    b.Property<int>("artist_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("artist_id"));

                    b.Property<string>("about")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artist_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artist_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("journey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("masterpiece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("masterpiece_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("artist_id");

                    b.ToTable("ArtistPortfolio");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.BidArtModel", b =>
                {
                    b.Property<int>("BidArt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidArt_id"));

                    b.Property<string>("BidArt_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidArt_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BidArtist_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidPrice")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BidArt_id");

                    b.ToTable("BidArt");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.BidPriceModel", b =>
                {
                    b.Property<int>("Bidprice_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bidprice_id"));

                    b.Property<string>("Art_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BidArt_id")
                        .HasColumnType("int");

                    b.Property<int>("Bidprice")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Bidprice_id");

                    b.ToTable("BidPrice");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.CartModel", b =>
                {
                    b.Property<int>("cart_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cart_id"));

                    b.Property<int>("art_id")
                        .HasColumnType("int");

                    b.Property<string>("art_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("cart_id");

                    b.HasIndex("art_id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.FavoritesModel", b =>
                {
                    b.Property<int>("fav_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fav_id"));

                    b.Property<int>("Artid")
                        .HasColumnType("int");

                    b.Property<int>("Userid")
                        .HasColumnType("int");

                    b.HasKey("fav_id");

                    b.HasIndex("Artid");

                    b.HasIndex("Userid");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.OrdersModel", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<string>("art_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("art_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("order_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("payment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_amount")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("order_id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.ReviewModel", b =>
                {
                    b.Property<int>("review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("review_id"));

                    b.Property<int>("Art_id")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<string>("reviewcomment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("review_id");

                    b.HasIndex("Art_id");

                    b.HasIndex("User_id");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.UsersModel", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<string>("user_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.CartModel", b =>
                {
                    b.HasOne("ArtVistaAPI.Models.ArtModel", "Art")
                        .WithMany()
                        .HasForeignKey("art_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Art");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.FavoritesModel", b =>
                {
                    b.HasOne("ArtVistaAPI.Models.ArtModel", "Art")
                        .WithMany()
                        .HasForeignKey("Artid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtVistaAPI.Models.UsersModel", "Users")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Art");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArtVistaAPI.Models.ReviewModel", b =>
                {
                    b.HasOne("ArtVistaAPI.Models.ArtModel", "Art")
                        .WithMany()
                        .HasForeignKey("Art_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtVistaAPI.Models.UsersModel", "Users")
                        .WithMany()
                        .HasForeignKey("User_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Art");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
